[package]
name = "rootserver"
version = "0.1.0"
edition = "2024"

[dependencies]
flume = "0.11.1"
log = "0.4.26"
pretty_env_logger = "0.5.0"
serde = "1.0.219"
serde_json = "1.0.140"
protocol = { path = "../protocol" }
shared = { path = "../shared" }
