[package]
name = "srbnfs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.32"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
protocol = { path = "../protocol" }
base64 = "0.22.1"
