[package]
name = "relayserver"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.32"
log = "0.4.26"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.219", features = ["derive"] }
protocol = { path = "../protocol" }
serde_json = "1.0.140"
